---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_issuer }}.yml"
env_file_name: "{{ service_issuer }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: issuer

docker_port: "{{ service_issuer_docker_port }}"
host_port: "{{ service_issuer_host_port }}"
image_name: "{{ image_issuer }}"
tag: "{{ tags_issuer }}"
replicas: "{{ service_replicas_issuer }}"
network_alias_name: "{{ network_alias_issuer }}"
docker_service_stack_name: frontend
docker_service_name: "{{ service_issuer }}"
force_reload: "{{ force_reload_issuer }}"
host_logs_location: "{{ issuer_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ ulp_bff_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"
