---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_verify }}.yml"
env_file_name: "{{ service_verify }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: verify

docker_port: "{{ service_verify_docker_port }}"
host_port: "{{ service_verify_host_port }}"
image_name: "{{ image_verify }}"
tag: "{{ tags_verify }}"
replicas: "{{ service_replicas_verify }}"
network_alias_name: "{{ network_alias_verify }}"
docker_service_stack_name: frontend
docker_service_name: "{{ service_verify }}"
force_reload: "{{ force_reload_verify }}"
host_logs_location: "{{ verify_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ ulp_bff_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"
