---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_bulk_issurance_service }}.yml"
env_file_name: "{{ service_bulk_issurance_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: bulk_issurance

docker_port: "{{ service_bulk_issurance_docker_port }}"
host_port: "{{ service_bulk_issurance_host_port }}"
image_name: "{{ image_bulk_issurance_service }}"
tag: "{{ tags_bulk_issurance_service }}"
replicas: "{{ service_replicas_bulk_issurance_service }}"
network_alias_name: "{{ network_alias_bulk_issurance_service }}"
docker_service_stack_name: ulp
docker_service_name: "{{ service_bulk_issurance_service }}"
force_reload: "{{ force_reload_bulk_issurance_service }}"
host_logs_location: "{{ bulk_issurance_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ ulp_bff_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"
